import { createAccount, createClient, generatePrivateKey } from "genlayer-js";
import { studioDevnet } from "genlayer-js/chains";

const contract=process.env.CONTRACT_ADDRESS?.trim(),raw=process.env.GENLAYER_PRIVATE_KEY?.trim().replace(/^['"]|['"]$/g,""),senderSource=process.env.SENDER_SOURCE?.trim(),receiverSource=process.env.RECEIVER_SOURCE?.trim();
if(!contract||!raw||!senderSource||!receiverSource)throw new Error("CONTRACT_ADDRESS, GENLAYER_PRIVATE_KEY, SENDER_SOURCE, and RECEIVER_SOURCE are required");
const keeper=setInterval(()=>{},60000),sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const key=raw.startsWith("0x")?raw:`0x${raw}`,receiverKey=generatePrivateKey();
const chain={...studioDevnet,id:61997,name:"GenLayer Studio Next",rpcUrls:{default:{http:["https://studio-next.genlayer.com/api"]}}};
const senderAccount=createAccount(key),receiverAccount=createAccount(receiverKey),sender=createClient({chain,account:senderAccount}),receiver=createClient({chain,account:receiverAccount});
const routeId=`relay-demo-${Date.now().toString(36)}`,handoffId="checkpoint-one",inspector="0x3333333333333333333333333333333333333333";console.log(`DEMO_ROUTE=${routeId}`);console.log(`RECEIVER=${receiverAccount.address}`);
async function finalized(client,hash){for(let attempt=0;attempt<300;attempt++){const receipt=await client.getTransaction({hash}).catch(()=>null);const status=String(receipt?.statusName??receipt?.status??"PENDING").toUpperCase();if(status==="FINALIZED")return receipt;if(["UNDETERMINED","DECLINED","CANCELED","CANCELLED"].includes(status))throw new Error(`Transaction ended ${status}`);await sleep(3000)}throw new Error("Transaction timed out before FINALIZED")}
async function write(client,label,functionName,args,intelligent=false){const fees=await client.estimateTransactionFees({leaderTimeunitsAllocation:intelligent?500n:180n,validatorTimeunitsAllocation:intelligent?650n:360n});const hash=await client.writeContract({address:contract,functionName,args,fees});console.log(`${label}_TX=${hash}`);const receipt=await finalized(client,hash);const status=String(receipt.statusName??receipt.status??"unknown"),execution=String(receipt.txExecutionResultName??receipt.txExecutionResult??"unknown"),consensus=String(receipt.resultName??receipt.result_name??"unknown");console.log(`${label}_STATUS=${status};EXECUTION_RESULT=${execution};CONSENSUS=${consensus}`);if(status!=="FINALIZED"||execution!=="FINISHED_WITH_RETURN"||consensus==="MAJORITY_DISAGREE")throw new Error(`${label} failed`);return hash}
const transferHash=await sender.transfer({to:receiverAccount.address,value:100000000000000000n});console.log(`FUND_RECEIVER_TX=${transferHash}`);await sleep(6000);
const senderObs={asset_id:"rotor-77",quantity:4,condition:"INTACT",identity_quote:"Asset ID: rotor-77",quantity_quote:"Quantity received for transfer: 4 sealed units",condition_quote:"Condition at departure: intact with security seal S-901"};
const receiverObs={asset_id:"rotor-77",quantity:4,condition:"INTACT",identity_quote:"Asset ID: rotor-77",quantity_quote:"Quantity counted at intake: 4 sealed units",condition_quote:"Condition at arrival: intact with security seal S-901"};
await write(sender,"CREATE_ROUTE","create_route",[routeId,"Rotor custody route","rotor-77",4,JSON.stringify([senderAccount.address,receiverAccount.address]),inspector]);
await write(sender,"PROPOSE_HANDOFF","propose_handoff",[routeId,handoffId,receiverAccount.address,senderSource,JSON.stringify(senderObs)]);
await write(receiver,"ACKNOWLEDGE_HANDOFF","acknowledge_handoff",[routeId,handoffId,receiverSource,JSON.stringify(receiverObs)],true);
const route=await sender.readContract({address:contract,functionName:"get_route",args:[routeId],jsonSafeReturn:true});const handoff=await sender.readContract({address:contract,functionName:"get_handoff",args:[routeId,handoffId],jsonSafeReturn:true});
console.log(`FINAL_ROUTE=${JSON.stringify(route)}`);console.log(`FINAL_HANDOFF=${JSON.stringify(handoff)}`);if(route.status!=="DELIVERED"||handoff.status!=="ACCEPTED"||handoff.result?.outcome!=="MATCH"||handoff.result?.source_receipts?.length!==2)throw new Error("Live custody transfer did not reach the expected state");clearInterval(keeper);
